### ISSUE TITLE
Update getComponents API method to support DEFAULT at root level

### ISSUE THREAD

**Issue by ShaneYu** [mertasan/tailwindcss-variables#119]
### Summary

The `getComponents` API method is awesome, however it takes the provided selector and concatenates that with each of the keys passed into the method. Whilst this is great, it would be really handy to be able to pass in a object where it has a `DEFAULT` property key which is used as the selector itself only.

For example, based on the documentation as it stands now, if you use `getComponents('.alert', { danger: { DEFAULT: {  background: 'red' }  } });` you will get `.alert-danger { background: red }`.

What I am proposing is the ability to use `getComponents('.alert', { DEFAULT: { background: 'gray' } })` which should give you `.alert { background: gray }`. Currently if you use `DEFAULT` like this, no CSS is added just for the selector `.alert`.

Here is a full example:

```javascript
const alert = {
  DEFAULT: {
    background: grey;
    border: 1px solid darkgrey;
  },
  "&.alert-danger": {
    background: pink;
    borderColor: red;
  }
};

addComponents(variablesApi.getComponents('.alert', alert));
``` 

Results in:

```css
.alert {
  background: grey;
  border: 1px solid darkgrey;
}

.alert.alert-danger {
  background: pink;
  border-color: red;
}
```

If it is already possible to achieve the above, it's not something I can work out from the documentation or from playing around with it. But this would be particularly handy; For now I am just using addComponents and building it up myself rather than using getComponents.

**Comment by ShaneYu** [comment]
After reading through the code of the `getComponents` method to understand how it works a bit better, I have managed to achieve what I've described above using the following:

```javascript
const alert = {
    DEFAULT: {
      DEFAULT: {
        color: "#000000",
        "&.alert-danger": {
          color: "#FF0000",
        },
      },
    },
  };

addComponents(getComponents(".alert", alert));
```

This results in:

```css
.alert {
  color: #000000;
}
.alert.alert-danger {
  color: #FF0000;
}
```

This is great as I can now achieve what I wanted to with it, however it feels odd to have to use two nested `DEFAULT` objects in order to achieve this. Since I can achieve it, I'll close this issue, however I do wonder if we could improve the usage for it in this scenario somehow?

**Comment by mertasan** [comment]
Hey Shane,

Thank you for reporting this. I'll consider what can be done about it. Feel free to submit a PR if you'd like.

Thank you.
