### ISSUE TITLE
No css variable fallback support.

### ISSUE THREAD

**Issue by mpalpha** [mertasan/tailwindcss-variables#26]
### Versions:
- Package Version: ?.?.?
- Tailwindcss Version: ?.?.?

### Description:

CSS variable fallback not supported.
e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/var#syntax

### Steps To Reproduce:
Try to use css fallbacks as per spec.
```
/* Fallback */
/* In the component's style: */
.component .header {
  color: var(--header-color, blue); /* header-color isn't set, and so remains blue, the fallback value */
}

.component .text {
  color: var(--text-color, black);
}

/* In the larger application's style: */
.component {
  --text-color: #080;
}
```
- …

**Comment by mpalpha** [comment]
Great plugin, but I can't use it currently due to this limitation.

**Comment by mertasan** [comment]
Hey Jason, thanks!

I made a few additions for Fallbacks. [v2.2.0](https://github.com/mertasan/tailwindcss-variables/releases/tag/v2.2.0)

You have to set the variables in the config file.

https://tailwindcss.com/docs/plugins#adding-components

Or you can use it like this:

```css
  .component .header {
    @apply text-red-400;
  }
```

Please check this: ee4225885c24fc7c23db5a3fabe1c44f8b60c793

or
[fallback.test.js](https://github.com/mertasan/tailwindcss-variables-actions/blob/master/__tests__/fallback.test.js)
[fallback.test.css](https://github.com/mertasan/tailwindcss-variables-actions/blob/master/__tests__/fallback.test.css)
[fallback.test.html](https://github.com/mertasan/tailwindcss-variables-actions/blob/master/__tests__/fallback.test.html)
