### ISSUE TITLE
No variables if base layer not used

### ISSUE THREAD

**Issue by 7iomka** [mertasan/tailwindcss-variables#34]
### Versions:
- Package Version: latest
- Tailwindcss Version: latest

### Description:

I disabled `@layer base` because preflight styles conflicts with verdor packages
And I don't see any css variable
Why?

**Comment by mertasan** [comment]
You could upgrade the package to `^2.3.0` and use it as follows. [`toBase`](https://github.com/mertasan/tailwindcss-variables#tobase)

```js
//...
plugins: [
  require('@mertasan/tailwindcss-variables')({
    toBase: false, // default: true
  })
]
//...
```
