### ISSUE TITLE
Only Default variables are added to output

### ISSUE THREAD

**Issue by christian-reichart** [mertasan/tailwindcss-variables#36]
### Versions:
- Package Version: 2.3.0
- Tailwindcss Version: 3.0.24

### Description:

When setting up my tailwind.config.js only variables default variables are outputted.

```
    variables: {
      DEFAULT: {
        'svg-logo-text': '#ECF2F4',
      },
      '.container': {
        'svg-logo-text': '#ECF2F4',
      }
    },
    darkVariables: {
      DEFAULT: {
        'svg-logo-text': '#ECF2F4',
      },
      '.container': {
        'svg-logo-text': '#ECF2F4',
      }
    },
```

Here I only get this output:
```
:root {
  --svg-logo-text: #ECF2F4;
}
```

Thanks for taking a look! <3

**Comment by christian-reichart** [comment]
Update: It now seems to be working, I updated Tailwind to 3.1.7.

I'm not sure if this is related to the update or somehow my tailwind generation script wasn't working correctly. I did however restart and rebuild a bunch of times when I was on version 3.0.24.

**Comment by mertasan** [comment]
Hi Christian,

I'm not sure there's anything that should be done here. Glad you got it resolved. Thanks for sharing the solution as well!
