### ISSUE TITLE
Keys are lowered case

### ISSUE THREAD

**Issue by NetanelBasal** [mertasan/tailwindcss-variables#37]
Thanks for this library.

### Versions:
- Package Version: 2.3.0
- Tailwindcss Version: latest

### Description:

When using the following config:

```ts
  theme: {
    variables: {
      DEFAULT: {
        UPPER: 'red'
      },
    },
  },
```

It generates it in lower case: `--upper: red`. The expected behavior is to generate the same key. Thanks.

**Comment by mertasan** [comment]
Hi @NetanelBasal , thank you.

Please upgrade the plugin to [^2.4.0](https://github.com/mertasan/tailwindcss-variables/releases/tag/v2.4.0) to fix this issue 👍

**Comment by NetanelBasal** [comment]
It works now. Thanks for the quick fix.
