### ISSUE TITLE
Is it possible to get dots working in the variable names?

### ISSUE THREAD

**Issue by sebpowell** [mertasan/tailwindcss-variables#39]
### Versions:
- Package Version: 2.3.0
- Tailwindcss Version: 3.1.6

### Question:

I'm trying to generate a variable name called --sizes-3.5 (and others like it – e.g. --sizes-0.5). Here's what I've tried:

```JSON
{
      "0.5": "2px",
      "3.5": "14px",
}
```

The output however, ignores the '.' – so I just get:

--sizes-05, --sizes-35, etc.

I also tried escaping the dot, but no luck. Any ideas?

**Comment by mertasan** [comment]
Hi Sebastien,

The variable syntax does not contain dots. Feel free to let me know if you have a specific use case for this.

https://developer.mozilla.org/en-US/docs/Web/CSS/--*

**Comment by mertasan** [comment]
![screenshot 6](https://user-images.githubusercontent.com/13007665/184372206-c33a8a93-a9f0-4ccd-800a-b1bb11398275.png)

**Comment by sebpowell** [comment]
Hey Mert, 

Thanks for the quick response! 

Ok, I see – the use case was wanting to mimick the classes that Tailwind generates (that includes half sizes – e.g. `.p-0.5`).

Prior to finding your plugin, I was generating all these variables myself, and I was able to get this working by escaping the '.' like so: `--sizes-0\.5` (I believe TW do this as well to generate their classes). See attached screenshot – this works fine. 

I actually tried generating them this way using your plugin, but found that the period simply gets ignored altogether. 

It's not a 'must-have' as I can find a way round it (I can simply write these variables manually somewhere), but thought it might make sense to add this in given that TW supports this with their classes.

**Comment by mertasan** [comment]
Thanks for explaining. This is very logical! Please wait for the next release.

**Comment by sebpowell** [comment]
@mertasan brilliant, thank you! Looking forward to it, let me know if you need any further input.

**Comment by mertasan** [comment]
@sebpowell 

Please upgrade the plugin to [^2.5.0](https://github.com/mertasan/tailwindcss-variables/releases/tag/v2.5.0) 🎉

**Comment by mertasan** [comment]
https://github.com/mertasan/tailwindcss-variables/blob/master/examples/simple/clean.css

**Comment by sebpowell** [comment]
@mertasan brilliant, thank you for getting that sorted so quickly! I'll give it a go tomorrow.
