### ISSUE TITLE
Support for PostCSS 7?

### ISSUE THREAD

**Issue by tvartom** [mertasan/tailwindcss-variables#4]
### Would it work to run with PostCSS

Thanks for a nice plugin!

The plugin is dependent on PostCSS ^8.2.9.

Vue (vue-cli) is stil dependent on PostCSS 7, so Tailwindcss needs to be used with Tailwind's PostCSS 7 compatibility build.
(Added with `npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9`, see https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)

Is PostCSS 8 strict needed for this plugin, or could the dependency by changed to be PostCSS 7 or 8 instead?

**Comment by mertasan** [comment]
if the tests are successful, I will publish a new version. thank you.

**Comment by mertasan** [comment]
@tvartom please upgrade the plugin to v1.1.3 👍
