### ISSUE TITLE
darkToRoot: true doesn't seem to be working.

### ISSUE THREAD

**Issue by isaiahdahl** [mertasan/tailwindcss-variables#53]
### Versions:
- Package Version: 2.5.1
- Tailwindcss Version: 3.2.4

### Description:

Can't seem to get this to work:

![CleanShot 2022-11-25 at 10 07 51](https://user-images.githubusercontent.com/23046374/204037426-dad21f9f-cf05-4b2c-9f1d-ef87388da57f.png)

### Steps To Reproduce:
Use the Tailwind Play. Set darkToRoot: true. 

Toggle the dark mode button in the tailwind play header. 

![CleanShot 2022-11-25 at 10 09 16](https://user-images.githubusercontent.com/23046374/204037560-bf2f78b2-c77e-4330-a9e1-331a5b09b0f7.png)

Which adds the 'dark' class on the html element. 

Unless I've misunderstood something that should then use the dark mode variables.

**Comment by mertasan** [comment]
Hi Isaiah,

I'm sorry you're having trouble.

But Playground seems to be causing it.

https://play.tailwindcss.com/rpHKQeOT6L?file=config

https://user-images.githubusercontent.com/13007665/204041004-6f391f12-9bbf-4523-aa3c-371ed2c720af.mov

**Comment by mertasan** [comment]
It worked as expected when used as below in Playground.

```html
<html class="dark">
    ...
</html>
```

https://play.tailwindcss.com/2nbWXc3BjO?file=config

![screenshot 68](https://user-images.githubusercontent.com/13007665/204048473-0e355990-937e-497b-85d0-7aff842e4c1b.png)

Additionally, the dark mode toggle button doesn't seem to work. But it works:

https://user-images.githubusercontent.com/13007665/204041004-6f391f12-9bbf-4523-aa3c-371ed2c720af.mov
